### ISSUE TITLE
Difference/improvements compared to nan0desu branches?

### ISSUE THREAD

**Issue by edrozenberg** [bytium/vm-host-modules#1]
I looked at the diffs between these two different projects, differences are minor, just curious how this compares to the similar work done by `nan0desu`

**Comment by bytium** [comment]
> I looked at the diffs between these two different projects, differences are minor, just curious how this compares to the similar work done by `nan0desu`

Sorry, I haven't checked his repo yet! I had to fix the compilation issues as fast as possible for Debian Testing.

Jobyer
