### ISSUE TITLE
VMware won't start at the end - Secure Boot?

### ISSUE THREAD

**Issue by maribox** [bytium/vm-host-modules#3]
Hey, 
at the end of the process, I get:
```
Starting vmware (via systemctl):  Job for vmware.service failed because the control process exited with error code.
See "systemctl status vmware.service" and "journalctl -xeu vmware.service" for details.
                                                           [FAILED]
```
If I look in the logs I get:
```
Sep 13 08:07:29 <username> vmware[147346]: Starting VMware services:
Sep 13 08:07:29 <username> vmware[147346]:    Virtual machine monitor[FEHLGESCHLAGEN]
Sep 13 08:07:29 <username> vmware[147346]:    Virtual machine communication interface[  OK  ]
Sep 13 08:07:29 <username> vmware[147346]:    VM communication interface socket family[  OK  ]
Sep 13 08:07:29 <username> vmware[147346]:    Virtual ethernet[FEHLGESCHLAGEN]
Sep 13 08:07:29 <username> vmware[147346]:    VMware Authentication Daemon[  OK  ]
Sep 13 08:07:29 <username> systemd[1]: vmware.service: Control process exited, code=exited, status=1/FAILURE
```
(FEHLGESCHLAGEN means FAILED, I don't know why it's using my native language here, my system language is set to english...)
I am on Fedora 40, kernel 6.9.7-200.fc40.x86_64.

I looked a bit around in the internet and the problem might be that I have secure boot enabled.
If I check with 
```
lsmod | grep vmmon
lsmod | grep vmnet
```
I get nothing, so the modules are not loaded, right?
If secure boot is the problem and I would need to sign the new compiled modules, it might be good to talk about this in the documentation a little bit for rookies like me, maybe explain what to do then or link a good article .

Thanks for your work!

**Comment by der-siebte-schatten** [comment]
Yes, you have to sign the modules and enroll them to your UEFI.
Just follow the steps here: https://thelinuxforum.com/articles/968-how-to-sign-vmware-workstation-pro-kernel-modules-on-uefi-secure-boot-enabled-linux-systems

You might want to bookmark this guide, as you will need to use it EACH TIME the modules are updated and compiled again

**Comment by maribox** [comment]
Thanks!

**Comment by jaclas** [comment]
I have the same issue on Kubuntu 24.04 LTS, but i don't use a secure boot, what's happen?

```
❯ mokutil --sb-state

SecureBoot disabled
Platform is in Setup Mode
```

```
❯ sudo systemctl status vmware
× vmware.service - LSB: This service starts and stops VMware services
     Loaded: loaded (/etc/init.d/vmware; generated)
     Active: failed (Result: exit-code) since Mon 2024-10-28 10:14:55 CET; 10min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 41324 ExecStart=/etc/init.d/vmware start (code=exited, status=1/FAILURE)
        CPU: 82ms

paź 28 10:14:54 aorus vmware[41324]:    VM communication interface socket family - done
paź 28 10:14:55 aorus vmware[41324]:    Virtual ethernet - failed
paź 28 10:14:55 aorus vmware[41324]:    VMware Authentication Daemon - done
paź 28 10:14:55 aorus systemd[1]: vmware.service: Control process exited, code=exited, status=1/FAILURE
paź 28 10:14:55 aorus systemd[1]: vmware.service: Failed with result 'exit-code'.
paź 28 10:14:55 aorus systemd[1]: vmware.service: Unit process 41395 (vmware-authdlau) remains running after unit stopped.
paź 28 10:14:55 aorus systemd[1]: vmware.service: Unit process 41396 (logger) remains running after unit stopped.
paź 28 10:14:55 aorus systemd[1]: vmware.service: Unit process 41399 (sh) remains running after unit stopped.
paź 28 10:14:55 aorus systemd[1]: vmware.service: Unit process 41401 (lsb_release) remains running after unit stopped.
paź 28 10:14:55 aorus systemd[1]: Failed to start vmware.service - LSB: This service starts and stops VMware services.

```

and modules are loaded:

```
❯ lsmod | egrep "vmmon|vmnet"
vmnet                  73728  9
vmmon                 167936  0

```

**Comment by maribox** [comment]
Because the link is dead, here's a short summary (for future me and others):

#### Get Module Code
```
cd $(mktemp -d)
git clone https://github.com/bytium/vm-host-modules.git
cd vm-host-modules
git checkout 17.6.2
```
**Run make**
Compile the modules into .ko files and copy the module source into .tar files.
```
make
```
Install the compiled vmmon.ko and vmnet.ko modules to /lib/modules/$(uname -r)/misc/
Copy the generated vmmon.tar and vmnet.tar files to /usr/lib/vmware/modules/source/
Run vmware-modconfig --console --install-all to update VMware with the new modules
```
sudo make install
```
#### Generate Key-Pair
```
openssl req -new -x509 -newkey rsa:2048 -keyout ~/.VMware-MOK.priv -outform DER -out ~/.VMware-MOK.der -nodes -days 36500 -subj "/CN=VMware/"
```
#### Sign Modules with Key-Pair and Sign-File 
This will hash the module, create a DER‑encoded PKCS#7 signature with the passed private key, and then appends a short metadata header, the signature, and the X.509 certificate to the end of the .ko file. When the kernel loads the module it locates that end, verifies the PKCS#7 blob against its trusted keyring (from the MOK List by the shim bootloader, see below), and only then allows the module to load. (The sign file gets updated often between different between kernel versions, which is why we're getting the currently used version with uname -r)
To see this you can also run `modinfo vmmon` before signing and after.
```
sudo /usr/src/kernels/$(uname -r)/scripts/sign-file sha256 ~/.VMware-MOK.priv ~/.VMware-MOK.der $(modinfo -n vmmon)
sudo /usr/src/kernels/$(uname -r)/scripts/sign-file sha256 ~/.VMware-MOK.priv ~/.VMware-MOK.der $(modinfo -n vmnet)
```
#### Import public key into shim bootloader MOK List
You can set a password, which you will be prompted for when enrolling the key after rebooting.
```
sudo mokutil --import ~/.VMware-MOK.der
sudo reboot
```
