### ISSUE TITLE
Can't build VMWare patched vmmon, vmnet per instructions

### ISSUE THREAD

**Issue by jimmiedave** [bytium/vm-host-modules#5]
Following instructions at https://bytium.com/vmware-workstation-host-module-patch-for-debian-and-ubuntu/

On a Ubuntu 22.04 LTS machine that initially built the VMWare stuff - it was working fine before kernel update - I can't compile given those instructions. I get "no rule to make...".

Same situation obtained when I started with a downloaded .zip instead of a cloned git repo.

```
person@machine:~/VMWare Patch$ cd vm-host-modules
person@machine:~/VMWare Patch/vm-host-modules$ git checkout 17.5.2
Branch '17.5.2' set up to track remote branch '17.5.2' from 'origin'.
Switched to a new branch '17.5.2'
person@machine:~/VMWare Patch/vm-host-modules$ make
make -C vmmon-only 
make[1]: Entering directory '/home/person/VMWare Patch/vm-host-modules/vmmon-only'
Using kernel build system.
make -C /lib/modules/6.8.0-45-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[2]: Entering directory '/usr/src/linux-headers-6.8.0-45-generic'
make[3]: *** No rule to make target 'Patch/vm-host-modules/vmmon-only'.  Stop.
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-45-generic'
make[1]: *** [Makefile:117: vmmon.ko] Error 2
make[1]: Leaving directory '/home/person/VMWare Patch/vm-host-modules/vmmon-only'
make: *** [Makefile:21: vmmon-only] Error 2
```
Any ideas appreciated.

Have been wondering: Should I just download VMWare Workstation again and install it over the prior copy? Will that work, or will I have the same problem?

**Comment by bytium** [comment]
> Following instructions at https://bytium.com/vmware-workstation-host-module-patch-for-debian-and-ubuntu/
> 
> On a Ubuntu 22.04 LTS machine that initially built the VMWare stuff - it was working fine before kernel update - I can't compile given those instructions. I get "no rule to make...".
> 
> Same situation obtained when I started with a downloaded .zip instead of a cloned git repo.
> 
> ```
> person@machine:~/VMWare Patch$ cd vm-host-modules
> person@machine:~/VMWare Patch/vm-host-modules$ git checkout 17.5.2
> Branch '17.5.2' set up to track remote branch '17.5.2' from 'origin'.
> Switched to a new branch '17.5.2'
> person@machine:~/VMWare Patch/vm-host-modules$ make
> make -C vmmon-only 
> make[1]: Entering directory '/home/person/VMWare Patch/vm-host-modules/vmmon-only'
> Using kernel build system.
> make -C /lib/modules/6.8.0-45-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
>   MODULEBUILDDIR= modules
> make[2]: Entering directory '/usr/src/linux-headers-6.8.0-45-generic'
> make[3]: *** No rule to make target 'Patch/vm-host-modules/vmmon-only'.  Stop.
> make[2]: *** [Makefile:240: __sub-make] Error 2
> make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-45-generic'
> make[1]: *** [Makefile:117: vmmon.ko] Error 2
> make[1]: Leaving directory '/home/person/VMWare Patch/vm-host-modules/vmmon-only'
> make: *** [Makefile:21: vmmon-only] Error 2
> ```
> 
> Any ideas appreciated.
> 
> Have been wondering: Should I just download VMWare Workstation again and install it over the prior copy? Will that work, or will I have the same problem?

Are you using vmware workstation version 17.5.2?

**Comment by jimmiedave** [comment]
![VMWare Workstation Version](https://github.com/user-attachments/assets/b3c2ab76-819a-4368-b996-94a04596e885)

On 17.5.2. 

Found  the answer, though: a space in the path to vm-host-modules. The clue (just spotted it as I was posting this) was:

`make[3]: *** No rule to make target 'Patch/vm-host-modules/vmmon-only'.  Stop.`

Folder path was "`VMWare Patch/vm-host-modules`...."

Didn't realize the "Patch" it was talking about was a borked version of my own folder name.

Fixed folder name and compiling now. Appreciate you providing this for everyone! Wish VMWare could get it together on this, but Broadcom is not exactly giving me confidence feels.

Thanks for looking. Sorry for any trouble.

**Comment by bytium** [comment]
> ![VMWare Workstation Version](https://private-user-images.githubusercontent.com/35353530/369714489-b3c2ab76-819a-4368-b996-94a04596e885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTA2MTYsIm5iZiI6MTcyNzA5MDMxNiwicGF0aCI6Ii8zNTM1MzUzMC8zNjk3MTQ0ODktYjNjMmFiNzYtODE5YS00MzY4LWI5OTYtOTRhMDQ1OTZlODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDExMTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYWY2M2IzYzI0NWMwYWMyMTViNWVjZmUwYTc4OGMxNTM4ZDAwNzJlYmM5MmI2OWIwYzEwOTI1OGQwN2Q4MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TC1il758nrKzjw20kiBF1vsvO_wFmDIl4yoQx9Xo038)
> 
> On 17.5.2.
> 
> Found the answer, though: a space in the path to vm-host-modules. The clue (just spotted it as I was posting this) was:
> 
> `make[3]: *** No rule to make target 'Patch/vm-host-modules/vmmon-only'. Stop.`
> 
> Folder path was "`VMWare Patch/vm-host-modules`...."
> 
> Didn't realize the "Patch" it was talking about was a borked version of my own folder name.
> 
> Fixed folder name and compiling now. Appreciate you providing this for everyone! Wish VMWare could get it together on this, but Broadcom is not exactly giving me confidence feels.
> 
> Thanks for looking. Sorry for any trouble.

Great to hear the problem is fixed!
