### ISSUE TITLE
Build fails with Linux 6.11.5

### ISSUE THREAD

**Issue by abdelouahabb** [bytium/vm-host-modules#9]
Workstation 17.6.1 and Linux 6.11.5, same error with Linux 6.8.0.48 (default Ubuntu 22.04 today)

```
03:48:10 abdelouahab@alien-popos vm-host-modules ±|17.6.1 ✗|
→ make
make -C vmmon-only 
make[1]: Entering directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
Using kernel build system.
make -C /lib/modules/6.11.5/build/include/.. M=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[2]: Entering directory '/home/abdelouahab/Desktop/linux-6.11.5'
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/apic.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/comport.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/cpuid.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/crosspage.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/memtrack.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/moduleloop.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o
/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o: warning: objtool: PhysTrack_Add() falls through to next function PhysTrack_Remove()
/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o: warning: objtool: PhysTrack_Remove() falls through to next function PhysTrack_Test()
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/sharedAreaVmmon.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/statVarsVmmon.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/task.o
/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/task.o: warning: objtool: .text: unexpected end of section
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/vmx86.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/bootstrap.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/monLoader.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/monLoaderVmmon.o
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/vmmblob.o
  LD [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.o
  MODPOST /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/Module.symvers
WARNING: Module.symvers is missing.
         Modules may not have dependencies or modversions.
         You may get many unresolved symbol errors.
         You can set KBUILD_MODPOST_WARN=1 to turn errors into warning
         if you want to proceed at your own risk.
ERROR: modpost: missing MODULE_LICENSE() in /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.o
ERROR: modpost: "HostIF_LookupUserMPN" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_GlobalLock" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_CancelWaitForThreads" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_AllocKernelPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_FreeContigPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "this_cpu_off" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_SemaphoreSignal" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_GetNumAnonPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "HostIF_LockPage" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
ERROR: modpost: "memcpy" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
WARNING: modpost: suppressed 62 unresolved symbol warnings because there were too many)
make[4]: *** [scripts/Makefile.modpost:145: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/Module.symvers] Error 1
make[3]: *** [/home/abdelouahab/Desktop/linux-6.11.5/Makefile:1878: modpost] Error 2
make[2]: *** [Makefile:224: __sub-make] Error 2
make[2]: Leaving directory '/home/abdelouahab/Desktop/linux-6.11.5'
make[1]: *** [Makefile:121: vmmon.ko] Error 2
make[1]: Leaving directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
make: *** [Makefile:24: vmmon-only] Error 2
```

Reverting to 17.5.2 and Kernel 6.8.0.48, I get an error too 
```

04:36:50 abdelouahab@alien-popos vm-host-modules ±|17.5.2 ✗|
→ make
make -C vmmon-only 
make[1]: Entering directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
Using kernel build system.
make -C /lib/modules/6.8.0-48-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
  MODULEBUILDDIR= modules
make[2]: Entering directory '/usr/src/linux-headers-6.8.0-48-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.o
/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.c:46:10: fatal error: driverLog.h: No such file or directory
   46 | #include "driverLog.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:243: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.8.0-48-generic/Makefile:1925: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only] Error 2
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-48-generic'
make[1]: *** [Makefile:117: vmmon.ko] Error 2
make[1]: Leaving directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
make: *** [Makefile:21: vmmon-only] Error 2
```

**Comment by Daniel-at-git** [comment]
On Linux 6.11.9 on Debian/sid I could compile it  (with some warnings) successful.

**Comment by bytium** [comment]
> Workstation 17.6.1 and Linux 6.11.5, same error with Linux 6.8.0.48 (default Ubuntu 22.04 today)
> 
> ```
> 03:48:10 abdelouahab@alien-popos vm-host-modules ±|17.6.1 ✗|
> → make
> make -C vmmon-only 
> make[1]: Entering directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
> Using kernel build system.
> make -C /lib/modules/6.11.5/build/include/.. M=$PWD SRCROOT=$PWD/. \
>   MODULEBUILDDIR= modules
> make[2]: Entering directory '/home/abdelouahab/Desktop/linux-6.11.5'
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/apic.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/comport.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/cpuid.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/crosspage.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/memtrack.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/moduleloop.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o
> /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o: warning: objtool: PhysTrack_Add() falls through to next function PhysTrack_Remove()
> /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/phystrack.o: warning: objtool: PhysTrack_Remove() falls through to next function PhysTrack_Test()
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/sharedAreaVmmon.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/statVarsVmmon.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/task.o
> /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/task.o: warning: objtool: .text: unexpected end of section
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/common/vmx86.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/bootstrap.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/monLoader.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/monLoaderVmmon.o
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/bootstrap/vmmblob.o
>   LD [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.o
>   MODPOST /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/Module.symvers
> WARNING: Module.symvers is missing.
>          Modules may not have dependencies or modversions.
>          You may get many unresolved symbol errors.
>          You can set KBUILD_MODPOST_WARN=1 to turn errors into warning
>          if you want to proceed at your own risk.
> ERROR: modpost: missing MODULE_LICENSE() in /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.o
> ERROR: modpost: "HostIF_LookupUserMPN" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_GlobalLock" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_CancelWaitForThreads" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_AllocKernelPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_FreeContigPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "this_cpu_off" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_SemaphoreSignal" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_GetNumAnonPages" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "HostIF_LockPage" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> ERROR: modpost: "memcpy" [/home/abdelouahab/Desktop/vm-host-modules/vmmon-only/vmmon.ko] undefined!
> WARNING: modpost: suppressed 62 unresolved symbol warnings because there were too many)
> make[4]: *** [scripts/Makefile.modpost:145: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/Module.symvers] Error 1
> make[3]: *** [/home/abdelouahab/Desktop/linux-6.11.5/Makefile:1878: modpost] Error 2
> make[2]: *** [Makefile:224: __sub-make] Error 2
> make[2]: Leaving directory '/home/abdelouahab/Desktop/linux-6.11.5'
> make[1]: *** [Makefile:121: vmmon.ko] Error 2
> make[1]: Leaving directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
> make: *** [Makefile:24: vmmon-only] Error 2
> ```
> 
> Reverting to 17.5.2 and Kernel 6.8.0.48, I get an error too
> 
> ```
> 
> 04:36:50 abdelouahab@alien-popos vm-host-modules ±|17.5.2 ✗|
> → make
> make -C vmmon-only 
> make[1]: Entering directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
> Using kernel build system.
> make -C /lib/modules/6.8.0-48-generic/build/include/.. M=$PWD SRCROOT=$PWD/. \
>   MODULEBUILDDIR= modules
> make[2]: Entering directory '/usr/src/linux-headers-6.8.0-48-generic'
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
>   CC [M]  /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.o
> /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.c:46:10: fatal error: driverLog.h: No such file or directory
>    46 | #include "driverLog.h"
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[4]: *** [scripts/Makefile.build:243: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only/linux/driver.o] Error 1
> make[3]: *** [/usr/src/linux-headers-6.8.0-48-generic/Makefile:1925: /home/abdelouahab/Desktop/vm-host-modules/vmmon-only] Error 2
> make[2]: *** [Makefile:240: __sub-make] Error 2
> make[2]: Leaving directory '/usr/src/linux-headers-6.8.0-48-generic'
> make[1]: *** [Makefile:117: vmmon.ko] Error 2
> make[1]: Leaving directory '/home/abdelouahab/Desktop/vm-host-modules/vmmon-only'
> make: *** [Makefile:21: vmmon-only] Error 2
> ```

Did you clone the right repo?

**Comment by Daniel-at-git** [comment]
IMHO we can close this issue. VMWare Workstation 17.6.2 is out und running fine. I need no patches with Linux 6.11 and 6.12.6
